language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO="django==1.6 --use-mirrors"
  - DJANGO="django==1.5.5 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install django-addresses django-extensions reportlab --use-mirrors
  - export PYTHONPATH=.

script:
  - python runtests.py
